In [1]:
import torch
X=torch.tensor([[0.1, 0.1], [0.1, 0.3], [0.3, 0.1]])
def softmax(X):
    X_exp = torch.exp(X)
    partition = X_exp.sum(1, keepdim=True)
    return X_exp / partition  # 这里应用了广播机制
torch.exp(X),torch.sum(torch.exp(X), dim=1, keepdim=True), softmax(X)

(tensor([[1.1052, 1.1052],
         [1.1052, 1.3499],
         [1.3499, 1.1052]]),
 tensor([[2.2103],
         [2.4550],
         [2.4550]]),
 tensor([[0.5000, 0.5000],
         [0.4502, 0.5498],
         [0.5498, 0.4502]]))

In [11]:
import torch
y_demo=torch.arange(6).reshape(2, 3)
x = torch.tensor([1,0])
y_demo,y_demo[[0,1],x]

(tensor([[0, 1, 2],
         [3, 4, 5]]),
 tensor([1, 3]))

In [21]:
y_hat_demo = torch.tensor([[0.1, 0.6, 0.3], [1.0, 0.0, 0.0]])
print(y_hat_demo.argmax(axis=1))
def cross_entropy(y_hat, y):
    """
    计算交叉熵损失。

    参数:
        y_hat: 形状为 (batch_size, num_classes) 的预测概率分布
        y:     形状为 (batch_size,) 的真实标签（整数，不是 one-hot 编码）

    返回:
        形状为 (batch_size,) 的张量，每个元素是该样本的交叉熵损失

    实现细节：
        range(len(y_hat)) 生成 [0, 1, 2, ..., batch_size-1] 的行索引
        y 提供列索引（即真实类别）
        y_hat[行索引, 列索引] 用高级索引一次性取出所有样本在真实类别上的概率
        -torch.log(...) 取负对数，得到每个样本的损失值
    """
    return -torch.log(y_hat[range(len(y_hat)), y])

# 验证：第一个样本真实类别的概率为 0.1，损失 = -ln(0.1) ≈ 2.3026
#       第二个样本真实类别的概率为 0.5，损失 = -ln(0.5) ≈ 0.6931
print("交叉熵损失:", cross_entropy(y_hat_demo, x))

tensor([1, 0])
交叉熵损失: tensor([0.5108, -0.0000])
