In [1]:
import os
os.makedirs(os.path.join('..', 'data'), exist_ok=True)
data_file = os.path.join('..', 'data', 'my_data.csv')
f=open(data_file, 'w')
f.write("id name age gender\n")
f.write("1 Alice NAN Female\n")
f.write("2 NAN 50 Male\n")
f.write("3 NAN 35 Male\n")
f.write("4 David NaN Male\n")
f.close()

In [ ]:
data_file, 
open(data_file).read()

('..\\data\\my_data.csv',
 'id name age gender\n1 Alice NAN Female\n2 NAN 50 Male\n3 NAN 35 Male\n4 David NaN Male\n')

In [8]:
import torch
a=torch.arange(20)
a=a.reshape(4, 5)
a,a.sum(),a.sum(axis=0),a.sum(axis=1)

(tensor([[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]]),
 tensor(190),
 tensor([30, 34, 38, 42, 46]),
 tensor([10, 35, 60, 85]))

In [ ]:
import torch
A=torch.arange(24).reshape(4,6)
sum_A = A.sum(axis=1, keepdims=True)
print(A/A.sum(axis=1, keepdims=True))
A,sum_A,A.cumsum(axis=1)#给出从左到右求和过程


tensor([[0.0000, 0.0667, 0.1333, 0.2000, 0.2667, 0.3333],
        [0.1176, 0.1373, 0.1569, 0.1765, 0.1961, 0.2157],
        [0.1379, 0.1494, 0.1609, 0.1724, 0.1839, 0.1954],
        [0.1463, 0.1545, 0.1626, 0.1707, 0.1789, 0.1870]])


(tensor([[ 0,  1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10, 11],
         [12, 13, 14, 15, 16, 17],
         [18, 19, 20, 21, 22, 23]]),
 tensor([[ 15],
         [ 51],
         [ 87],
         [123]]),
 tensor([[  0,   1,   3,   6,  10,  15],
         [  6,  13,  21,  30,  40,  51],
         [ 12,  25,  39,  54,  70,  87],
         [ 18,  37,  57,  78, 100, 123]]))

In [46]:
x=torch.arange(4)
y=x.reshape(2,2)
print(id(x))
print(id(y))
x.shape,x,x.T

2265159812496
2265159609776


(torch.Size([4]), tensor([0, 1, 2, 3]), tensor([0, 1, 2, 3]))

In [52]:
import torch
x=torch.tensor([[0.0, 1.0], [2.0, 3.0]])
y=torch.tensor([[0.0, 2.0], [4.0, 6.0]])
x<=y

tensor([[True, True],
        [True, True]])

In [ ]:
import torch
x=torch.tensor([[0.0, 1.0], [2.0, 3.0], [4.0, 5.0]])
y=torch.tensor([[1]])
print(x.shape, y.shape),print(x,y)
x,y,x+y

torch.Size([3, 2]) torch.Size([1, 1])
tensor([[0., 1.],
        [2., 3.],
        [4., 5.]]) tensor([[1]])


(tensor([[0., 1.],
         [2., 3.],
         [4., 5.]]),
 tensor([[1]]),
 tensor([[1., 2.],
         [3., 4.],
         [5., 6.]]),
 3,
 1)

In [61]:
import torch
x=torch.arange(12).reshape(4,1,-1)
len(x),x.shape,x,x.sum(axis=0),x.sum(axis=1),x.sum(axis=2)

(4,
 torch.Size([4, 1, 3]),
 tensor([[[ 0,  1,  2]],
 
         [[ 3,  4,  5]],
 
         [[ 6,  7,  8]],
 
         [[ 9, 10, 11]]]),
 tensor([[18, 22, 26]]),
 tensor([[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]]),
 tensor([[ 3],
         [12],
         [21],
         [30]]))

In [3]:
import torch
x=torch.arange(24).reshape(2,3,4)
print("x=")
print(x),print("x.shape=",x.shape)
print("x.sum()=")
print(x.sum()),print("x.sum().shape=",x.sum().shape)
print("x.sum(axis=0)=")
print(x.sum(axis=0)),print("x.sum(axis=0).shape=",x.sum(axis=0).shape)
print("x.sum(axis=1)=") 
print(x.sum(axis=1)),print("x.sum(axis=1).shape=",x.sum(axis=1).shape)
print("x.sum(axis=2)=")
print(x.sum(axis=2)),print("x.sum(axis=2).shape=",x.sum(axis=2).shape)
print("x.sum(axis=[0,1])=")
print(x.sum(axis=[0,1])),print("x.sum(axis=[0,1]).shape=",x.sum(axis=[0,1]).shape)
print("x.sum(axis=[0,2])=")
print(x.sum(axis=[0,2])),print("x.sum(axis=[0,2]).shape=",x.sum(axis=[0,2]).shape)
print("x.sum(axis=[1,2])=")
print(x.sum(axis=[1,2])),print("x.sum(axis=[1,2]).shape=",x.sum(axis=[1,2]).shape)
print("x.sum(axis=[0,1,2])=")
print(x.sum(axis=[0,1,2])),print("x.sum(axis=[0,1,2]).shape=",x.sum(axis=[0,1,2]).shape)
print("x.sum(axis=0, keepdims=True)=")
print(x.sum(axis=0, keepdims=True)),print("x.sum(axis=0, keepdims=True).shape=",x.sum(axis=0, keepdims=True).shape)
print("x.sum(axis=1, keepdims=True)=")
print(x.sum(axis=1, keepdims=True)),print("x.sum(axis=1, keepdims=True).shape=",x.sum(axis=1, keepdims=True).shape)
print("x.sum(axis=2, keepdims=True)=")
print(x.sum(axis=2, keepdims=True)),print("x.sum(axis=2, keepdims=True).shape=",x.sum(axis=2, keepdims=True).shape)

x=
tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
x.shape= torch.Size([2, 3, 4])
x.sum()=
tensor(276)
x.sum().shape= torch.Size([])
x.sum(axis=0)=
tensor([[12, 14, 16, 18],
        [20, 22, 24, 26],
        [28, 30, 32, 34]])
x.sum(axis=0).shape= torch.Size([3, 4])
x.sum(axis=1)=
tensor([[12, 15, 18, 21],
        [48, 51, 54, 57]])
x.sum(axis=1).shape= torch.Size([2, 4])
x.sum(axis=2)=
tensor([[ 6, 22, 38],
        [54, 70, 86]])
x.sum(axis=2).shape= torch.Size([2, 3])
x.sum(axis=[0,1])=
tensor([60, 66, 72, 78])
x.sum(axis=[0,1]).shape= torch.Size([4])
x.sum(axis=[0,2])=
tensor([ 60,  92, 124])
x.sum(axis=[0,2]).shape= torch.Size([3])
x.sum(axis=[1,2])=
tensor([ 66, 210])
x.sum(axis=[1,2]).shape= torch.Size([2])
x.sum(axis=[0,1,2])=
tensor(276)
x.sum(axis=[0,1,2]).shape= torch.Size([])
x.sum(axis=0, keepdims=True)=
tensor([[[12, 14, 16, 18],
         [20, 22, 24, 26],


(None, None)

In [5]:
import torch
x=torch.arange(24).reshape(3,2,-1)
print(x),
len(x),x.shape

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7]],

        [[ 8,  9, 10, 11],
         [12, 13, 14, 15]],

        [[16, 17, 18, 19],
         [20, 21, 22, 23]]])


(3, torch.Size([3, 2, 4]))