In [65]:
import numpy as np #导入必要的运行库
import pandas as pd

#np.random.seed(42)      #设置随机数种子，保证每次运行结果一致（可选）

a  = np.random.randn(2)

df = pd.read_csv('Salary_Data.csv') #你可以通过pandas读取本文件夹内的数据，也可以自行构建数据或是使用kaggle的数据集，教程在实践引导中
learning_rate = 0.1 #学习率
epochs = 2000 #迭代次数

if_normalize=1 #如果x和y都进行标准化，则设置if_normalize=1
if if_normalize==1: #标准化，即 (x-均值)/标准差，将x，y化为0均值，1方差分布
    df_unnormalized = df.copy()
    df['YearsExperience'] = (df['YearsExperience']-df['YearsExperience'].mean())/df['YearsExperience'].std()
    df['Salary'] = (df['Salary']-df['Salary'].mean())/df['Salary'].std()

for i in range(epochs):
    loss_vector = df['Salary']-a[0]*df['YearsExperience']-a[1]
    loss = np.sum(loss_vector**2)/len(loss_vector)  #损失函数


    gradient_a0 = -2*np.mean((df['Salary']-a[0]*df['YearsExperience']-a[1])*df['YearsExperience']) #用数学方法计算梯度
    gradient_a1 = -2*np.mean(df['Salary']-a[0]*df['YearsExperience']-a[1])


    a[0] = a[0] - learning_rate*gradient_a0 #更新参数
    a[1] = a[1] - learning_rate*gradient_a1

    if i % 100 == 0: #每100个epoch打印一次损失
        print(f'Epoch {i}, Loss: {loss}')

if if_normalize==1: #如果x和y都进行标准化，则需要将参数a进行还原
    a[0] = a[0] * df_unnormalized['YearsExperience'].std() + df_unnormalized['YearsExperience'].mean()
    a[1] = a[1] * df_unnormalized['Salary'].std() + df_unnormalized['Salary'].mean()

print(a)
print(loss)

Epoch 0, Loss: 3.4988634350449592
Epoch 100, Loss: 0.041608557994608414
Epoch 200, Loss: 0.04160855799460842
Epoch 300, Loss: 0.04160855799460842
Epoch 400, Loss: 0.04160855799460842
Epoch 500, Loss: 0.04160855799460842
Epoch 600, Loss: 0.04160855799460842
Epoch 700, Loss: 0.04160855799460842
Epoch 800, Loss: 0.04160855799460842
Epoch 900, Loss: 0.04160855799460842
Epoch 1000, Loss: 0.04160855799460842
Epoch 1100, Loss: 0.04160855799460842
Epoch 1200, Loss: 0.04160855799460842
Epoch 1300, Loss: 0.04160855799460842
Epoch 1400, Loss: 0.04160855799460842
Epoch 1500, Loss: 0.04160855799460842
Epoch 1600, Loss: 0.04160855799460842
Epoch 1700, Loss: 0.04160855799460842
Epoch 1800, Loss: 0.04160855799460842
Epoch 1900, Loss: 0.04160855799460842
[8.08947364e+00 7.60030000e+04]
0.04160855799460842


In [66]:
import torch
a  = torch.randn(2)
data = pd.read_csv("data.csv")
print(data)

   Y   X1   X2
0 -2 -4.4 -3.2
1 -1 -2.3 -1.1
2  0  0.1  0.9
3  1  2.9  2.8


In [67]:
my_y=data.iloc[:,0]
my_x=data.iloc[:,1:3]
print(my_y)
print(my_x)

0   -2
1   -1
2    0
3    1
Name: Y, dtype: int64
    X1   X2
0 -4.4 -3.2
1 -2.3 -1.1
2  0.1  0.9
3  2.9  2.8


In [68]:
data_x=torch.tensor(my_x.to_numpy(dtype=float))
data_y=torch.tensor(my_y.to_numpy(dtype=float))
data_x=data_x.T
print(data_x)
print(data_y)

tensor([[-4.4000, -2.3000,  0.1000,  2.9000],
        [-3.2000, -1.1000,  0.9000,  2.8000]], dtype=torch.float64)
tensor([-2., -1.,  0.,  1.], dtype=torch.float64)


In [69]:
weight = torch.randn(2,dtype=float, requires_grad=True) #随机初始化权重，并设置requires_grad=True以便后续计算梯度
bias = torch.randn(1, dtype=float, requires_grad=True)  #随机初始化偏置，并设置
print(weight,weight.shape)
print(bias,bias.shape)
print(data_x,data_x.shape)
weight.T@data_x+bias

tensor([-0.7279,  0.6169], dtype=torch.float64, requires_grad=True) torch.Size([2])
tensor([-1.6607], dtype=torch.float64, requires_grad=True) torch.Size([1])
tensor([[-4.4000, -2.3000,  0.1000,  2.9000],
        [-3.2000, -1.1000,  0.9000,  2.8000]], dtype=torch.float64) torch.Size([2, 4])


tensor([-0.4321, -0.6652, -1.1783, -2.0443], dtype=torch.float64,
       grad_fn=<AddBackward0>)

In [70]:
def loss(weight, bias, x, y):
    return torch.mean((weight.T@x+bias-y)**2) #定义损失函数 
my_loss=loss(weight, bias, data_x, data_y)
print(my_loss)

tensor(3.3066, dtype=torch.float64, grad_fn=<MeanBackward0>)


In [71]:
my_loss.backward() #反向传播计算梯度
print(weight.grad) #打印权重的梯度
print(bias.grad) #打印偏置的梯度

tensor([-8.3076, -7.4850], dtype=torch.float64)
tensor([-1.1599], dtype=torch.float64)


In [251]:
lr=0.001 #学习率
times=100 #迭代次数
while   times>0:
    my_loss=loss(weight, bias, data_x, data_y) #计算损失
    my_loss.backward() #反向传播计算梯度
    with torch.no_grad(): #更新参数
        weight -= lr*weight.grad
        bias -= lr*bias.grad
    weight.grad.zero_() #清零梯度
    bias.grad.zero_()
    if times % 10 == 0: #每10个epoch打印一次损失
        print(f'Epoch {100-times:10.0f},w0: {weight[0].item():5.4f}, w1: {weight[1].item():5.4f}, b: {bias.item():5.4f}, Loss: {my_loss.item():5.4f}')
    times-=1

Epoch          0,w0: 0.0773, w1: 0.4061, b: -0.3679, Loss: 0.0000
Epoch         10,w0: 0.0773, w1: 0.4061, b: -0.3679, Loss: 0.0000
Epoch         20,w0: 0.0774, w1: 0.4061, b: -0.3679, Loss: 0.0000
Epoch         30,w0: 0.0774, w1: 0.4061, b: -0.3679, Loss: 0.0000
Epoch         40,w0: 0.0774, w1: 0.4060, b: -0.3679, Loss: 0.0000
Epoch         50,w0: 0.0774, w1: 0.4060, b: -0.3679, Loss: 0.0000
Epoch         60,w0: 0.0774, w1: 0.4060, b: -0.3679, Loss: 0.0000
Epoch         70,w0: 0.0774, w1: 0.4060, b: -0.3679, Loss: 0.0000
Epoch         80,w0: 0.0774, w1: 0.4060, b: -0.3679, Loss: 0.0000
Epoch         90,w0: 0.0774, w1: 0.4060, b: -0.3679, Loss: 0.0000
